project_id = "jztypotqkrcvpevuhwqh"

[functions.copilot]
verify_jwt = false

[functions.scheduler]
verify_jwt = false

[functions.search-index]
verify_jwt = false

[functions.semantic-search]
verify_jwt = false